-- Supprimer les tables dans l'ordre inverse de leur dépendance
DROP TABLE IF EXISTS works_on CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS equipment CASCADE;
DROP TABLE IF EXISTS terminal CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS container CASCADE;
DROP TABLE IF EXISTS package CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS storage_space CASCADE;
DROP TABLE IF EXISTS storage_zone CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

-- Supprimer les types ENUM
DROP TYPE IF EXISTS SEXE CASCADE;
DROP TYPE IF EXISTS EQUIPMENT_MODEL CASCADE;
DROP TYPE IF EXISTS EQUIPMENT_STATUS CASCADE;
DROP TYPE IF EXISTS SPACE_TYPE CASCADE;
DROP TYPE IF EXISTS EMPLOYEE_POSTE CASCADE;
DROP TYPE IF EXISTS ITEM_STATUS CASCADE;
DROP TYPE IF EXISTS SUPPLIER_TYPE CASCADE;
