-- Truncate des tables dépendantes fortes
TRUNCATE TABLE works_on RESTART IDENTITY CASCADE;
TRUNCATE TABLE "order" RESTART IDENTITY CASCADE;
TRUNCATE TABLE item RESTART IDENTITY CASCADE;

-- Truncate des tables dépendantes faibles
TRUNCATE TABLE equipment RESTART IDENTITY CASCADE;
TRUNCATE TABLE terminal RESTART IDENTITY CASCADE;
TRUNCATE TABLE employee RESTART IDENTITY CASCADE;
TRUNCATE TABLE supplier RESTART IDENTITY CASCADE;
TRUNCATE TABLE address RESTART IDENTITY CASCADE;
TRUNCATE TABLE container RESTART IDENTITY CASCADE;
TRUNCATE TABLE package RESTART IDENTITY CASCADE;
TRUNCATE TABLE item RESTART IDENTITY CASCADE;
TRUNCATE TABLE storage_space RESTART IDENTITY CASCADE;
TRUNCATE TABLE storage_zone RESTART IDENTITY CASCADE;

-- Truncate des tables principales/utilisateurs
TRUNCATE TABLE user_activity RESTART IDENTITY CASCADE;
TRUNCATE TABLE "user" RESTART IDENTITY CASCADE;


-- Supprimer les tables dans l'ordre inverse de leur dépendance
DROP TABLE IF EXISTS works_on CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS equipment CASCADE;
DROP TABLE IF EXISTS terminal CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS container CASCADE;
DROP TABLE IF EXISTS package CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS storage_space CASCADE;
DROP TABLE IF EXISTS storage_zone CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS user_activity CASCADE;

-- Supprimer les types ENUM
DROP TYPE IF EXISTS SEXE CASCADE;
DROP TYPE IF EXISTS EQUIPMENT_MODEL CASCADE;
DROP TYPE IF EXISTS EQUIPMENT_STATUS CASCADE;
DROP TYPE IF EXISTS SPACE_TYPE CASCADE;
DROP TYPE IF EXISTS EMPLOYEE_POSTE CASCADE;
DROP TYPE IF EXISTS ITEM_STATUS CASCADE;
DROP TYPE IF EXISTS SUPPLIER_TYPE CASCADE;